ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

[IMPORTANT]
.Comment utiliser ce modèle
====
Effacez les paragraphes ou les phrases qui ne sont pas applicables à votre courrier. Replacez les XXX. Envoyez par email, ou par courrier (recommandé).
====

[NOTE]
Coordonnées, numéro de client et de contrat si applicable.

John Doe +
Adresse +
CP Ville

Ville, le XXX

_Référence_ : Client XXX Contrat XXX


_Concerne_ : **Droit d'accès à mes données à caractère personnel (RGPD)**

[NOTE]
.Apostrophe
Choisissez la plus spécifique.

Madame la Déléguée à la Protection des données, + 
Monsieur le Délégué à la Protection des données, + 
Madame, + 
Monsieur, +

Je vous écris pour exercer mon droit d'accès aux données à caractère personnel me concernant. Je souhaite connaître la nature exacte des données personnelles que vous détenez à mon sujet. Ma demande est basée sur le Règlement UE 2016/679 du 27 avril 2016 (RGPD).

\1. Obtention d'une copie

Veuillez me fournir une copie de toutes les données personnelles que vous avez me concernant, y compris, sans s'y limiter :

- Les informations me concernant que vous avez collectées ;
- Les raisons pour lesquelles vous utilisez ces informations ;
- Les personnes ou entités avec lesquelles vous partagez ces informations ;
- La source de ces informations, si elles n'ont pas été collectées directement auprès de moi.

Ceci sous une forme électronique d'usage courant, lisible par un humain et interprétable aisément par une machine, dans un format structuré, et de préférence par voie électronique.

\2. Opposition au marketing direct

Je m'oppose au traitement à des fins de prospection et de marketing, y compris au profilage dans la mesure où il est lié à une telle prospection.

\3. Identification

[TIP]
Certains responsables de traitement exigeront une copie de votre carte d'identité pour répondre à votre demande. Vous pouvez soit vous y plier, soit proposer d'emblée une alternative, au risque de vous voir opposer une fin de non-recevoir (possiblement abusive) et de perdre un tour.

[NOTE]
.Carte d'identité
Si vous acceptez d'envoyer une copie de votre carte d'identité.

Vous trouverez ci-joint une copie de ma carte d'identité.

[NOTE]
.Justificatif d'identité
Si vous préférez ne pas envoyer une copie de votre carte d'identité, il peut être utile d'anticiper un refus de votre demande.

Vous êtes tenu de prendre toutes les mesures raisonnables pour vérifier l'identité d'une personne concernée qui demande l'accès à des données. La CNIL a cependant estimé qu'une demande systématique d'un justificatif d'identité n’était pas justifiée dès lors qu’il n’existe pas de doute sur l’identité la personne exerçant ses droits (sanction contre Carrefour France, 26 novembre 2020).

[NOTE]
Si votre adresse email est connue.

Vous pouvez envoyer les fichiers à l'adresse email XXX renseignée dans vos fichiers.

[NOTE]
.Belgique - carte d'identité électronique eID.
Signature életronique légalement valable, mais je doute que la moindre entreprise soit capable de vérifier la signature.

La présente demande est signée électroniquement au moyen de ma carte d'identité électronique.

[NOTE]
Carte de fidélité

Dès lors, je joins une copie de ma carte de fidélité.

[NOTE]
.Formule de politesse
Identique à l'introduction.

Je vous prie d'agréer, Madame, Monsieur, l'expression de mes meilleures salutations.

XXX John Doe

XXX (Signé électroniquement eID)
